### PR TITLE
Change strongbranching pseudo_candidate default

### LINKED ISSUE #238: Inconsistent default for pseudo_candidates
## Describe the bug
The flag `pseudo_candidates` is set to `False` by default in some places, for example in [`ecole.environment.Branching`](https://github.com/ds4dm/ecole/blob/c1f8a534546999ab14bed482e55f633a78962fe5/libecole/include/ecole/dynamics/branching.hpp#L18) and [`ecole.observation.Khalil2016`](https://github.com/ds4dm/ecole/blob/c1f8a534546999ab14bed482e55f633a78962fe5/libecole/include/ecole/observation/khalil-2016.hpp#L111), while it is set to `True` by default in some other places, for example in [`ecole.observation.StrongBranchingScores`](https://github.com/ds4dm/ecole/blob/c1f8a534546999ab14bed482e55f633a78962fe5/libecole/include/ecole/observation/strongbranchingscores.hpp#L17). This can be confusing and lead to unexpected results / behaviors when someone instantiates everything with the default values.

## Setting
- Ecole version: 7.0.3

## Expected behavior
`pseudo_candidates` should always be set to `False` by default,  everywhere.

## Additional context
See the discussion [here](https://github.com/ds4dm/ml4co-competition/discussions/62).

### PR DESCRIPTION
**Pull request by AntoinePrv**
## Pull request checklist

- [x] I have opened an issue to discuss the proposed changes: Fix #238.
- [ ] I have modified/added tests to cover the new changes/features.
- [ ] I have modified/added the documentation to cover the new changes/features.
- [x] I have ran the tests, checks, and code formatters.

### CODE REVIEW

**Comment by gasse** [comment]
Looks good to me. However, shouldn't that be merged into `dev` to target the next major release ?

**Review by gasse — COMMENTED** [review]
LGTM

**Comment by AntoinePrv** [comment]
Isn't this a bug fix for `7.0.4` ?

**Comment by gasse** [comment]
It's API breaking, it will require users to update their code. I would rather wait for the end of the competition before making such a change.

**Comment by gasse** [comment]
The idea being that we keep the 7.0.x releases for bugfixes related to the competition.

**Comment by AntoinePrv** [comment]
Indeed. So guess you **don't** want this for the competition.

**Pull request merged**
