### PR TITLE
Documentation: theory page

### PR DESCRIPTION
**Pull request by gasse**
## Pull request checklist
- [ ] I have checked that the documentation compiles on the CI server (LaTex libraries for rendreing math might be missing)

This is a first draft, I tried to be clear and concise. Let me know what you think !

### CODE REVIEW

**Comment by AntoinePrv** [comment]
I see the error
```
LaTeX command 'latex' cannot be run (needed for math display), check the imgmath_latex setting
```
Does the documentation build correctly on your computer? Latex would be a dependency for `math` instructions?
Perhaps we can substitute to MathJax, may be a lighter solution

**Comment by gasse** [comment]
Yes on my laptop it works fine. I'll try to switch to Mathjax, however I am not sure I can use the latex customization I am using now. I'll let you know. Otherwise, do you think it could be reasonable to have a working (minimal) latex distro within the CI chain ?

**Comment by AntoinePrv** [comment]
So I tried the current branch on my computer (with Latex) and it did not work. I don't look forward to fighting with Latex inside the CI environment.

With MathJax, I replaced
```python
extensions += ["sphinx.ext.imgmath"]
imgmath_image_format = "svg"
```
With 
```python
extensions += ["sphinx.ext.mathjax"]
```
And it worked directly, except for the preamble that is not supported.
Could we not inline it's content? `argmax` does not seem very complicated to reproduce.
What is `nindep` supposed to do?

**Comment by AntoinePrv** [comment]
Also, I've been using "Ecole" (v.s. "ECOLE") in text to refer to the library. I believe should decide on one and stay homogeneous.

**Comment by gasse** [comment]
I got rid of LaTex, let me know if that works for you.
I also changed ECOLE for Ecole, I agree it looks best in the text.

Note: equation numbers do not render properly, this seems to be an old bug of the Sphinx theme we are using:
https://github.com/readthedocs/sphinx_rtd_theme/pull/383

Probably we could fix it by tweaking the CSS a bit. Or we can just wait for a fix.

**Comment by AntoinePrv** [comment]
Seems to work, I'm rebasing to fix the CI.

I have the same bug of equation number, I'll try to see If I can add the CSS from the issue.

**Comment by gasse** [comment]
There was still a glitch with chrome, I tweaked a bit the CSS, looks like it fixed it. All good for me, you can merge @AntoinePrv if you want

**Review by PhantomRwcwride2Zero — COMMENTED** [review]
Sorry there is no merging when that pull happen because that was things that someone stole from me and we was just trying to get them back

**Pull request merged**
