### PR TITLE
Unstable/pickle

### LINKED ISSUE #106: Add pickle support for NodeBipartiteObs
## Describe the problem or improvement suggested
Add pickle support for NodeBipartiteObs.

## Describe the solution you would like
- [ ] Using pybind support of pickle through serialization. Need that it is supported on xtensor's end.
- [ ] Edit branching tutorial to pickle observation directly

## Describe alternatives you have considered
When returning an `NodeBipartiteObs`, dynamically move it to a  `PyNodeBipartiteObs` where the `xtensor`s have been replaced by `pyxtensor`, and let xtensor-python do the rest.

## Additional context
Please comment with other classes that could use it. It is not added by default because it needs to list all the attributes, which is bit redundant.

### PR DESCRIPTION
**Pull request by AntoinePrv**
## Pull request checklist

- [x] I have open an issue to discuss the proposed changes. Fix #106
- [x] I have modified/added tests to cover the new changes/features.
- [ ] I have modified/added the documentation to cover the new changes/features.
- [x] I have ran the tests, checks, and code formatters.

## Proposed implementation
The pickle and copy functions have been bound from Pybind

## Alternative
Given that we don't need the observation back in C++, we could bind it with a [Python 3.7+ `dataclass`](https://docs.python.org/3/library/dataclasses.html)
```cpp

py::exec(R"python(
  import dataclasses

  import numpy

  @dataclasses.dataclass
  class NodeBipartiteObs
      column_features: numpy.ndarray
      rows_features: numpy.ndarray
      ...
  )python", m.attr("__dict__") );
  
  py::class_<NodeBipartite>(m, "NodeBipartite")
    .def("extract", [m](NodeBipartite& self, scip::Model& model, ...){
      auto [column_features, ...] = self.extract(model, ...)
      return m.attr("NodeBipartiteObs")(py::arg(column_features) = column_features), ...);
    });
```

This would make it possible to do things like
```python 
obs = obs.apply(torch.from_numpy).float().to(device)
```
(because Python typing is weaker than C++).

### CODE REVIEW

**Comment by AntoinePrv** [comment]
@dchetelat this should cover the pickling of `NodeBipartite`. Could you edit the tutorial accordingly (in this branch)? I had a look but was a bit lost.

**Comment by dchetelat** [comment]
Done! You can merge I think.

**Comment by AntoinePrv** [comment]
Thanks! Is it an improvement in term of code?

I'm going to edit #147 to add pickle support as well.

**Comment by dchetelat** [comment]
> Thanks! Is it an improvement in term of code?

I would say so, the code is cleaner :-)

**Pull request merged**
