### PR TITLE
Add empty substitution on empty arrays in run.sh

### LINKED ISSUE #230: Cannot run tests with dev/run.sh (script error)
When running `dev/run.sh` for tests, I get the error message `extra_args[@]: unbound variable`.

For example,
```
>./dev/run.sh test-lib
cmake --build build --parallel --target ecole-lib-test
    [  0%] Built target ecole-lib-version
    [  1%] Building CXX object libecole/CMakeFiles/ecole-lib.dir/src/version.cpp.o
    [  2%] Building CXX object libecole/CMakeFiles/ecole-lib.dir/src/dynamics/branching.cpp.o
    [  3%] Linking CXX static library libecole.a
    [ 44%] Built target ecole-lib
    Consolidate compiler generated dependencies of target ecole-lib-test
    [ 45%] Linking CXX executable ecole-lib-test
    [100%] Built target ecole-lib-test
./dev/run.sh: line 180: extra_args[@]: unbound variable
```
and
```
>./dev/run.sh test-py                                                                                    
cmake --build build --parallel --target ecole-py-ext
    [  2%] Copying Python files                                                                                                                                
    [  2%] Built target ecole-py-files   
    [  2%] Built target ecole-lib-version                                                                                                                      
    [ 79%] Built target ecole-lib                                       
    Consolidate compiler generated dependencies of target ecole-py-ext                                                                                         
    [100%] Built target ecole-py-ext            
./dev/run.sh: line 211: extra_args[@]: unbound variable         
```

# Settings
On a RedHat distribution with git version 2.30.2 and bash version 4.2.46.

### PR DESCRIPTION
**Pull request by AntoinePrv**
## Pull request checklist

- [x] I have opened an issue to discuss the proposed changes: Fix  #230
- [x] ~I have modified/added tests to cover the new changes/features.~
- [x] ~I have modified/added the documentation to cover the new changes/features.~
- [x] I have ran the tests, checks, and code formatters.

## Proposed implementation
As suggested by https://stackoverflow.com/a/61551944/5862073

### CODE REVIEW

**Comment by AntoinePrv** [comment]
@dchetelat do you want to try this PR before we merge.

**Comment by dchetelat** [comment]
It seems to work now, except that it throws this error early on now:
```
>./dev/run.sh test-lib
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
cmake --build build --parallel --target ecole-lib-test
    [  0%] Built target ecole-lib-version
    [ 44%] Built target ecole-lib
    [ 45%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/main.cpp.o
    [ 46%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/test-utility/tmp-folder.cpp.o
    [ 49%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/conftest.cpp.o
    [ 49%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/test-traits.cpp.o
    [ 50%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/test-random.cpp.o
    [ 51%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/utility/test-vector.cpp.o
    [ 53%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/utility/test-chrono.cpp.o
    [ 54%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/utility/test-random.cpp.o
    [ 55%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/utility/test-graph.cpp.o
    [ 57%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/scip/test-scimpl.cpp.o
    [ 58%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/scip/test-model.cpp.o
    [ 59%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/instance/unit-tests.cpp.o
    [ 62%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/instance/test-files.cpp.o
    [ 62%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/instance/test-independent-set.cpp.o
    [ 63%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/instance/test-set-cover.cpp.o
    [ 64%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/instance/test-combinatorial-auction.cpp.o
    [ 66%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/instance/test-capacitated-facility-location.cpp.o
    [ 67%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/data/test-constant.cpp.o
    [ 72%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/data/test-vector.cpp.o
    [ 74%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/data/test-timed.cpp.o
    [ 75%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/reward/test-lpiterations.cpp.o
    [ 76%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/reward/test-nnodes.cpp.o
    [ 77%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/reward/test-isdone.cpp.o
    [ 79%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/reward/test-solvingtime.cpp.o
    [ 80%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/reward/test-boundintegral.cpp.o
    [ 81%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/data/test-map.cpp.o
    [ 83%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/data/test-parser.cpp.o
    [ 85%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/observation/test-nodebipartite.cpp.o
    [ 85%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/observation/test-milpbipartite.cpp.o
    [ 85%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/data/test-none.cpp.o
    [ 71%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/data/test-tuple.cpp.o
    [ 85%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/data/test-multiary.cpp.o
    [ 87%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/observation/test-strongbranchingscores.cpp.o
    [ 88%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/observation/test-pseudocosts.cpp.o
    [ 89%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/observation/test-khalil-2016.cpp.o
    [ 90%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/dynamics/test-branching.cpp.o
    [ 92%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/observation/test-hutter-2011.cpp.o
    [ 93%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/dynamics/test-branching-sum.cpp.o
    [ 94%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/dynamics/test-configuring.cpp.o
    [ 96%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/dynamics/test-primalsearch.cpp.o
    [ 97%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/environment/test-environment.cpp.o
    [ 98%] Building CXX object libecole/tests/CMakeFiles/ecole-lib-test.dir/src/utility/test-sparse-matrix.cpp.o
    [100%] Linking CXX executable ecole-lib-test
    [100%] Built target ecole-lib-test
build/libecole/tests/ecole-lib-test
    ===============================================================================
    All tests passed (1880287 assertions in 110 test cases)
```
and
```
>./dev/run.sh test-py
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
cmake --build build --parallel --target ecole-py-ext
    [  2%] Copying Python files
    [  2%] Built target ecole-py-files
    [  2%] Built target ecole-lib-version
    [ 79%] Built target ecole-lib
    Consolidate compiler generated dependencies of target ecole-py-ext
    [100%] Built target ecole-py-ext
export PYTHONPATH=build/python
python -m pytest
    ========================================================================================================== test session starts ===========================================================================================================
    platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
    rootdir: /local1/chetdidi/ecole
    plugins: helpers-namespace-0.0.0, anyio-2.2.0
    collected 289 items                                                                                                                                                                                                                      
    
    python/tests/test_data.py ..................                                                                                                                                                                                       [  6%]
    python/tests/test_dynamics.py ..........................................                                                                                                                                                           [ 20%]
    python/tests/test_environment.py ....                                                                                                                                                                                              [ 22%]
    python/tests/test_information.py ....                                                                                                                                                                                              [ 23%]
    python/tests/test_instance.py s....s....s...................                                                                                                                                                                       [ 33%]
    python/tests/test_observation.py ...............................................                                                                                                                                                   [ 50%]
    python/tests/test_random.py ......                                                                                                                                                                                                 [ 52%]
    python/tests/test_reward.py ...........................................................................................................                                                                                            [ 89%]
    python/tests/test_scip.py ............................                                                                                                                                                                             [ 98%]
    python/tests/test_version.py ..s                                                                                                                                                                                                   [100%]
    
    ==================================================================================================== 285 passed, 4 skipped in 19.38s =====================================================================================================
unset PYTHONPATH
```

**Comment by AntoinePrv** [comment]
Ha OK, this one is the git error.

**Review by dchetelat — APPROVED** [review]
Seems good now.

**Pull request merged**
