### PR TITLE
Configuring tutorial

### PR DESCRIPTION
**Pull request by gasse**
This is the configuring tutorial. Please someone try it on your machine see if everything works fine. It requires the latest version of Ecole, `scikit-optimize` and `matplotlib`.

### CODE REVIEW

**Comment by gasse** [comment]
Closes #60

**Comment by dchetelat** [comment]
Small comments:

- I think it's not very aesthetically pleasing that the blue line goes on top of the legend:
image

- Maybe we should have a list at the start of the tutorial of all the libraries that need to be installed for it, because it's annoying to be in the middle of the tutorial, realize you have forgotten to install something, install it and have to restart the runtime.

- You only evaluate in number of nodes, maybe we can add time evaluation?

- There's an empty cell at the end.

Otherwise it looks good to me!

**Comment by gasse** [comment]
Done. Thanks!

**Review by AntoinePrv — APPROVED** [review]
I quite like the way you setup the environment, very readable!
Othewise, I think the following could improve the tutorial:
- Add versions of the libraries used, perhaps in the form of an (inline) `environment.yaml` conda file? Let's do the same with @dchetelat tutorial. I would add the `ecole` and `python`.
  version in there as well.
- In the graph, I am not sure what the axis are. x is the parameter value, right? Also would it make sense to change the legend `Observation` to `reward`?

**Comment by dchetelat** [comment]
Also there is a small typo, "branc-and-bound" just after the second cell.

**Comment by gasse** [comment]
Ok I think I addressed all the points you raised. I went for just giving the list of packages+version numbers, which does not assume users are using a specific package manager (conda or pip).

Let me know if it's ok now. Thanks for the feedback guys !

**Comment by jdumouchelle** [comment]
The tutorial looks good to me.  I ran in on my computer with no issues.

**Comment by gasse** [comment]
Thanks @AntoinePrv !

**Pull request merged**
